### ISSUE TITLE
checkpoint seem broken.

### ISSUE THREAD

**Issue by bychen7** [dulucas/UVO_Challenge#3]
this checkpoint([seg_swin_l_mixed_pretrained.pth](https://drive.google.com/file/d/1XKpm_VLLJ0mkgN9ZTDErG-4XuQHib_GK/view?usp=sharing)) seem broken.
```python
import torch
torch.load('seg_swin_l_mixed_pretrained.pth')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chen/miniconda3/envs/sota/lib/python3.9/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/chen/miniconda3/envs/sota/lib/python3.9/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by dulucas** [comment]
Hi, I pushed a new [checkpoint](https://drive.google.com/file/d/1DCMUWSbNyNJfjneitUMUrJzrOb9C3n_M/view), could you try it please?

**Comment by bychen7** [comment]
> Hi, I pushed a new [checkpoint](https://drive.google.com/file/d/1DCMUWSbNyNJfjneitUMUrJzrOb9C3n_M/view), could you try it please?

it's ok, thanks.
